"""
Django settings for hirunnerbackend project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import datetime
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOGGING_DIR = os.path.join(BASE_DIR,'logs') # 存储日志的内容

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&_*8f-)+lcs2=0mm+b9*=_91wt9i^li7p%h0$2zzw%453q4!1_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # 跨域访问
    'user.apps.UserConfig',  # 用户模块
    'hirunner.apps.HirunnerConfig',
    'channels',  # websocket
    'django_apscheduler',

    'rest_framework', # DRF模块
    'drf_yasg', # API文档生成器，用于调试，与rest_framework一起使用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 跨域访问
]

ROOT_URLCONF = 'hirunnerbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hirunnerbackend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'PORT': 3306,
        'NAME': 'hirunner',
        'USER': 'hirunner',
        'PASSWORD': 'Ch8d%hdhxt'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# ---------------- 时区配置开始 ---------------------

LANGUAGE_CODE = 'zh-hans' # 中文

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# ---------------- 时区配置结束 ---------------------

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# ---------------- 用户认证鉴权配置开始 ---------------------

AUTH_USER_MODEL = 'user.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'user.authentications.CustomJSONWebTokenAuthentication',
    ),
    'EXCEPTION_HANDLER': 'user.utils.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'user.pagination.CustomPagination',
    'PAGE_SIZE': 10
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=30),
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(hours=24),
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'user.utils.jwt_response_payload_handler',
    "JWT_AUTH_HEADER_PREFIX": "Bearer"
}

# ---------------- 用户认证鉴权配置开始 ---------------------

# ---------------- 跨域访问配置开始 ---------------------

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ()

# ---------------- 跨域访问配置结束 ---------------------


# ---------------- websocket配置开始 ---------------------
ASGI_APPLICATION = 'hirunnerbackend.asgi.application'  # ASGI应用配置

# 一种通信系统
CHANNEL_LAYERS = {
    "default": {
        # InMemoryChannelLayer 内存
        "BACKEND": "channels.layers.InMemoryChannelLayer",

        # RedisChannelLayer Redis（生产建议用这个）
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        #     "hosts": [("127.0.0.1", 6379)],
        # },
    }
}
# ---------------- websocket配置结束 ---------------------

# -----------------日志配置开始------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters':{
        'standard':{
            'format': '%(asctime)s [%(levelname)s][%(name)s:%(lineno)d][process_id:thread_id]:%(message)s'
        }
    },
    'handlers':{
        'console':{
            'class': 'logging.StreamHandler',
        },
        'file':{
            'class': 'logging.FileHandler',
            'filename': f'{LOGGING_DIR}/record.log'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    },
}
# -----------------日志配置结束------------------------

DPMS_DB_CONFIG = {
    "ip":"localhost",
    "port":3306,
    "user":"smart_qms",
    "passwd":"Ch8d%hdhxt",
    "dbname":"dpms_cdp"
}

PRODUCT_PULL_VERSION_CRON = "0 */1 * * *"

# jenkins配置
JENKINS_BASE_URL = "http://192.168.1.9:8080"
JENKINS_JOB_NAME = "hirunner_run_python_job"
JENKINS_JOB_EXCUTE_URL = f"{JENKINS_BASE_URL}/view/hirunner/job/{JENKINS_JOB_NAME}"